name: Hello GitHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

  on:
  schedule:
    - cron: "0 0 * * *"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print
        run: echo "Hello, GitHub Actions!"


   
