name: Hello GitHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    env:
     GREETING: "hello from gitHub Action"

    steps:
      - uses: actions/checkout@v4

      - name: Print name
        run: echo "nico!"

      - name: Print surname
        run: echo "Khoza!"


   
